<?php
	include('functioncall.php');
	$title = 'Terms and Condition';
	$menu = 'terms';
	include('header.php');
?>	
	<section>
		<div class="container">
			<div class="row">				
				<?php //include('category.php'); ?>
				<div class="col-sm-12">
					<div class="blog-post-area">
						<h2 class="title text-center">Terms and Condition</h2>
						<div class="single-blog-post">
							<!-- <h2>Terms and Condition</h2> -->
							<p>Nattupuram is the licensed owner of the brand and logo nattupuram.com and the website nattupuram.com</p> <br>
							<p>In order to access and use our website services and stuffs, you have accepted the following terms and conditions. These Terms apply to all visitors, users and others who access or use the Service. You are therefore advised to read carefully these terms and conditions every time you use the www.nattupuram.com website operated by Nattupuram.</p> <br>
							<p><strong>Eligibility:</strong></p><br>
							<p>The User certifies that he/she is at least 18 (eighteen) years of age. If your age is below 18 years your parents or legal guardians can transact on behalf of you if they are registered users. You are prohibited from purchasing any material which is for adult consumption and the sale of which to minors is prohibited.</p> <br>
							<p><strong>Color Discrepancy:</strong></p><br>
							<p>We are giving maximum effort to display the color of our products that appear on our website as accurately as possible. However, as the actual colors you see will depend on your monitor, we cannot guarantee that your monitor's display of color will be accurate.
							</p><br>
							<p><strong>Governing Law and Jurisdiction:</strong></p><br>
							<p>This User Agreement shall be construed in accordance with the applicable laws of India. The Courts at Tamil Nadu shall have exclusive jurisdiction in any proceedings arising out of this agreement.</p><br>
							<p><strong>Indemnity:</strong><p></br>
							<p>You agree to defend, indemnify and hold harmless  NATTUPURAM, its employees, directors, officers, agents and their successors and assigns from and against any and all claims, liabilities, damages, losses, costs and expenses, including attorney’s fees, caused by or arising out of claims based upon your actions or inactions, which may result in any loss or liability to NATTUPURAM or any third party including but not limited to breach of any warranties, representations or undertakings or in relation to the non-fulfillment of any of your obligations under this User Agreement or arising out of the your violation of any applicable laws, regulations including but not limited to Intellectual Property Rights, payment of statutory dues and taxes, claim of libel, defamation, violation of rights of privacy or publicity, loss of service by other subscribers and infringement of intellectual property or other rights. This clause shall survive the expiry or termination of this User Agreement.</p>
							<p><strong>Purchases/Cancellation/Contents:</strong></p>
							<p>The prices and availability of products are subject to change without prior notice at the sole discretion of "NATTUPURAM". We reserves the right to refuse or cancel any order placed for a product that is listed at an incorrect price or for any other reason. This shall be regardless of whether the order has been confirmed and/or payment been received. The payment shall be refunded and the User shall be informed of the same. Request for cancellations of orders once placed on site shall be entertained only if your order hasn't already been dispatched. The User agrees to give accurate, authentic and true information. We reserves the right to confirm and validate the information and other details provided by the User at any point of time. If any such User details are found not to be true wholly or partly We have the right in its sole discretion to reject the registration and debar the User from using the services of www.nattupuram.com without prior intimation whatsoever. Our Service allows you to post, link, store, share and otherwise make available certain information, text, graphics, videos, or other material (“Content”). You are responsible for the contents that you post within our website.</p>
							<p><strong>Non liability Clauses:</strong></p>
							<p>We are not responsible for any damage suffered by users from use of the services on www.nattupuram.com. This without limitation includes loss of revenue or data resulting from delays, non-deliveries, missed deliveries, or service interruptions as may occur because of any act / omission of the vendor. This disclaimer of liability also applies to any damages or injury caused by any failure of performance, negligence, defect, deletion, error, omission, interruption, delay in operation or transmission, computer virus, communication line failure, theft or destruction or unauthorized access to, alteration of, or use of record, whether for breach of contract, tortuous behavior, or under any other cause of action.</p>
							<p><strong>Testimonial (Reviews/Feedback) Submissions:</strong></p>
							<p>All reviews, comments, feedback, postcards, suggestions, ideas, and other submissions disclosed, submitted or offered to the Site on or by this Site or otherwise disclosed, submitted or offered in connection with your use of this Site (collectively, the “Comments”) shall be and remain the property of NATTUPURAM. Such disclosure, submission or offer of any Comments shall constitute an assignment to NATTUPURAM of all worldwide rights, titles and interests in all copyrights and other intellectual properties in the Comments. Thus, NATTUPURAM owns exclusively all such rights, titles and interests and shall not be limited in any way in its use, commercial or otherwise, of any Comments. NATTUPURAM will be entitled to use, reproduce, disclose, modify, adapt, create derivative works from, publish, display and distribute any Comments you submit for any purpose whatsoever, without restriction and without compensating you in any way. NATTUPURAM is and shall be under no obligation (1) to maintain any Comments in confidence; (2) to pay you any compensation for any Comments; or (3) to respond to any Comments. You agree that any Comments submitted by you to the Site will not violate this policy or any right of any third party, including copyright, trademark, privacy or other personal or proprietary right(s), and will not cause injury to any person or entity. You further agree that no Comments submitted by you to the Website will be or contain libelous or otherwise unlawful, threatening, abusive or obscene material, or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any form of “spam”.</p>
							<p>NATTUPURAM does not regularly review posted Comments, but does reserve the right (but not the compulsion) to monitor and edit or remove any Comments submitted to the Site. You grant NATTUPURAM the right to use the name that you submit in connection with any Comments. You agree not to use a false email address, impersonate any person or entity, or otherwise mislead as to the origin of any Comments you submit. You are and shall remain solely responsible for the content of any Comments you make and you agree to indemnify NATTUPURAM and its affiliates for all claims resulting from any Comments you submit. NATTUPURAM and its affiliates take no responsibility and assume no liability for any Comments submitted by you or any third party.</p>
							<p><strong>Delayed Delivery:</strong></p>
							<p>If a non-delivery or late delivery occurs due to a mistake by the User (i.e. wrong or incomplete name or address or recipient not available) any extra cost spent by Us for re-delivery shall be claimed from the User placing the order.</p>
							<p><strong>Third party :</strong></p>
							<p>We are not legally responsible for any type or kind of credit card fraud. The liability to use a card fraudulently will be on the user and the onus to 'prove otherwise' shall be exclusively on the user. The User must exclusively use his/her own card on the site.</p>
							<p><strong>Copyright & Trademark:</strong></p>
							<p>Nattupuram, its authorized suppliers and licensors expressly reserve all intellectual property rights in all text, programs, products, processes, technology, content and other materials, which appear on this Site. Access to this Website does not confer and shall not be considered as conferring upon anyone any license under any of NATTUPURAM or any third party’s intellectual property rights. All rights, including copyright, in this website are owned by or licensed to NATTUPURAM. Any use of this website or its contents, including copying or storing it or them in whole or part, other than for your own personal, non-commercial use is prohibited without the permission of NATTUPURAM. You may not modify, distribute or re-post anything on this website for any purpose. The names and logos and all related product and service names, design marks and slogans are the trademarks or service marks of NATTUPURAM, its affiliates, its partners or its suppliers. All other marks are the property of their respective companies. No trademark or service mark license is granted in connection with the materials contained on this Site. Access to this Site does not authorize anyone to use any name, logo or mark in any manner.</p>
							<p><strong>Modification of Terms & Conditions of Service:</strong></p>
							<p>We reserves the right to add, delete, alter or modify these terms and conditions at any time. You should regularly review the Terms & Conditions on the Site. In the event the modified Terms & Conditions is not acceptable to you, you should discontinue using the Service. However, if you continue to use the Service you shall be deemed to have agreed to accept and abide by the modified Terms & Conditions of Use of this Site.</p>
						</div><!--/blog-post-area-->
					</div><!--/Repaly Box-->
				</div>	
			</div>
		</div>
	</section>	
<?php
	include('footer.php');
?>